# Generated by Django 4.0.3 on 2022-03-30 05:21

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.upload_location),
        ),
    ]
